SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SPECIALITIES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPECIALITIES] ADD  CONSTRAINT [PK_SPECIALITIES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TEACHERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRSTNAME] [nvarchar](50) NULL,
	[LASTNAME] [nvarchar](50) NULL,
	[PHONE_NUMBER] [nvarchar](50) NULL,
	[ADRESS] [nvarchar](50) NULL,
	[SPECIALITY_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEACHERS] ADD  CONSTRAINT [PK_TEACHERS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEACHERS]  WITH CHECK ADD  CONSTRAINT [FK_TEACHERS_SPECIALITIES] FOREIGN KEY([SPECIALITY_ID])
REFERENCES [dbo].[SPECIALITIES] ([ID])
GO
ALTER TABLE [dbo].[TEACHERS] CHECK CONSTRAINT [FK_TEACHERS_SPECIALITIES]
GO

CREATE TABLE [dbo].[REGIONS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REGIONS] ADD  CONSTRAINT [PK_REGIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PREFECTURES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NULL,
	[REGION_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PREFECTURES] ADD  CONSTRAINT [PK_PREFECTURES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PREFECTURES]  WITH CHECK ADD  CONSTRAINT [FK_PREFECTURES_REGIONS] FOREIGN KEY([REGION_ID])
REFERENCES [dbo].[REGIONS] ([ID])
GO
ALTER TABLE [dbo].[PREFECTURES] CHECK CONSTRAINT [FK_PREFECTURES_REGIONS]
GO

CREATE TABLE [dbo].[CITIES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NULL,
	[REGION_ID] [int] NULL,
	[PREFECTURE_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CITIES] ADD  CONSTRAINT [PK_CITIES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CITIES]  WITH CHECK ADD  CONSTRAINT [FK_CITIES_PREFECTURES] FOREIGN KEY([PREFECTURE_ID])
REFERENCES [dbo].[PREFECTURES] ([ID])
GO
ALTER TABLE [dbo].[CITIES] CHECK CONSTRAINT [FK_CITIES_PREFECTURES]
GO
ALTER TABLE [dbo].[CITIES]  WITH CHECK ADD  CONSTRAINT [FK_CITIES_REGIONS] FOREIGN KEY([REGION_ID])
REFERENCES [dbo].[REGIONS] ([ID])
GO
ALTER TABLE [dbo].[CITIES] CHECK CONSTRAINT [FK_CITIES_REGIONS]
GO

CREATE TABLE [dbo].[STUDENTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRSTNAME] [nvarchar](50) NULL,
	[LASTNAME] [nvarchar](50) NULL,
	[DATE_OF_BIRTH] [date] NULL,
	[MARRIED] [nvarchar](50) NULL,
	[GENDER] [nvarchar](50) NULL,
	[PHONE_NUMBER] [nvarchar](50) NULL,
	[ADDRESS] [nvarchar](50) NULL,
	[REGION_ID] [int] NULL,
	[PREFECTURE_ID] [int] NULL,
	[CITY_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STUDENTS] ADD  CONSTRAINT [PK_STUDENTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STUDENTS]  WITH CHECK ADD  CONSTRAINT [FK_STUDENTS_REGIONS] FOREIGN KEY([REGION_ID])
REFERENCES [dbo].[REGIONS] ([ID])
GO
ALTER TABLE [dbo].[STUDENTS] CHECK CONSTRAINT [FK_STUDENTS_REGIONS]
GO

CREATE TABLE [dbo].[TEACHERS_STUDENTS](
	[TEACHER_ID] [int] NOT NULL,
	[STUDENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [nvarchar](50) NULL,
	[DAY] [nvarchar](50) NULL,
	[TIME] [nvarchar](50) NULL,
	[ROOM] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEACHERS_STUDENTS] ADD  CONSTRAINT [PK_TEACHERS_STUDENTS] PRIMARY KEY CLUSTERED 
(
	[TEACHER_ID] ASC,
	[STUDENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEACHERS_STUDENTS]  WITH CHECK ADD  CONSTRAINT [FK_TEACHERS_STUDENTS_STUDENTS] FOREIGN KEY([STUDENT_ID])
REFERENCES [dbo].[STUDENTS] ([ID])
GO
ALTER TABLE [dbo].[TEACHERS_STUDENTS] CHECK CONSTRAINT [FK_TEACHERS_STUDENTS_STUDENTS]
GO
ALTER TABLE [dbo].[TEACHERS_STUDENTS]  WITH CHECK ADD  CONSTRAINT [FK_TEACHERS_STUDENTS_TEACHERS] FOREIGN KEY([TEACHER_ID])
REFERENCES [dbo].[TEACHERS] ([ID])
GO
ALTER TABLE [dbo].[TEACHERS_STUDENTS] CHECK CONSTRAINT [FK_TEACHERS_STUDENTS_TEACHERS]
GO

CREATE TABLE [dbo].[COURSES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [nvarchar](50) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COURSES] ADD  CONSTRAINT [PK_COURSES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE TABLE [dbo].[STUDENTS_COURSES](
	[STUDENT_ID] [int] NOT NULL,
	[COURSE_ID] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STUDENTS_COURSES] ADD  CONSTRAINT [PK_STUDENTS_COURSES] PRIMARY KEY CLUSTERED 
(
	[STUDENT_ID] ASC,
	[COURSE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[STUDENTS_COURSES]  WITH CHECK ADD  CONSTRAINT [FK_STUDENTS_COURSES_COURSES] FOREIGN KEY([COURSE_ID])
REFERENCES [dbo].[COURSES] ([ID])
GO
ALTER TABLE [dbo].[STUDENTS_COURSES] CHECK CONSTRAINT [FK_STUDENTS_COURSES_COURSES]
GO
ALTER TABLE [dbo].[STUDENTS_COURSES]  WITH CHECK ADD  CONSTRAINT [FK_STUDENTS_COURSES_STUDENTS] FOREIGN KEY([STUDENT_ID])
REFERENCES [dbo].[STUDENTS] ([ID])
GO
ALTER TABLE [dbo].[STUDENTS_COURSES] CHECK CONSTRAINT [FK_STUDENTS_COURSES_STUDENTS]
GO





