export interface Person {
    givenName: string;
    surName: string;
    age: number;
    email: string;
    address: string;
}

export interface EPerson {
    givenName: string;
    surName: string;
    age: string;
    email: string;
    address: string;
}

export const ManyPerson: EPerson[] = [
    {
        givenName: "Grigorios",
        surName: "Gkoura",
        email: "Gkouras@icloud.com",
        age: "26",
        address: "Road1",
    },
    {
        givenName: "Ava",
        surName: "Wood",
        email: "ava_wood@live.com",
        age: "52",
        address: "Gifford",
    },
    {
        givenName: "Amanda",
        surName: "Johnson",
        email: "a.a@outlook.com",
        age: "35",
        address: "Monrovia",
    },
    {
        givenName: "Layla",
        surName: "Powell",
        email: "laylakpowell45@rocketmail.com",
        age: "72",
        address: "Cando",
    },
    {
        givenName: "Oliver",
        surName: "Harris",
        email: "oharris@hotmail.com",
        age: "63",
        address: "Palms",
    },
    {
        givenName: "Natalie",
        surName: "Price",
        email: "natalie_l30@live.com",
        age: "39",
        address: "Showell",
    },
    {
        givenName: "Timothy",
        surName: "Carter",
        email: "timothycarter68@ymail.com",
        age: "73",
        address: "Incline Village",
    },
    {
        givenName: "Thomas",
        surName: "Rogers",
        email: "thomas_alan_rogers@rocketmail.com",
        age: "60",
        address: "Prineville",
    },
    {
        givenName: "Claire",
        surName: "Adams",
        email: "claire_m_adams@gmail.com",
        age: "77",
        address: "Wofford Heights",
    },
    {
        givenName: "Timothy",
        surName: "Jones",
        email: "tmjones@hotmail.com",
        age: "59",
        address: "Hampton Falls",
    },
    {
        givenName: "Rachel",
        surName: "Robinson",
        email: "r_robinson@outlook.com",
        age: "69",
        address: "Fresno",
    },
    {
        givenName: "Austin",
        surName: "Diaz",
        email: "adiaz@live.com",
        age: "31",
        address: "Happy",
    },
    {
        givenName: "Robert",
        surName: "Murphy",
        email: "robert.murphy@hotmail.com",
        age: "68",
        address: "Harrod",
    },
    {
        givenName: "Timothy",
        surName: "Morris",
        email: "t.a.morris@live.com",
        age: "71",
        address: "Ft Mitchell",
    },
    {
        givenName: "Mateo",
        surName: "Diaz",
        email: "mateo_diaz@gmail.com",
        age: "60",
        address: "Wendell",
    },
    {
        givenName: "Kelsey",
        surName: "Williams",
        email: "k.m@yahoo.com",
        age: "45",
        address: "Winchester Center",
    },
    {
        givenName: "Danielle",
        surName: "Henderson",
        email: "danielle.henderson@live.com",
        age: "56",
        address: "Las Cruces",
    },
    {
        givenName: "Jeremy",
        surName: "Morgan",
        email: "jmorgan@hotmail.com",
        age: "50",
        address: "Fairfax",
    },
    {
        givenName: "Jonathan",
        surName: "Williams",
        email: "jonathan.robert.williams@aol.com",
        age: "69",
        address: "Piney View",
    },
    {
        givenName: "Victoria",
        surName: "Lopez",
        email: "victoria_rose_lopez59@aol.com",
        age: "65",
        address: "Phillips",
    },
    {
        givenName: "David",
        surName: "Russell",
        email: "david_russell@yahoo.com",
        age: "52",
        address: "Lake City",
    },
    {
        givenName: "James",
        surName: "Patterson",
        email: "j.w@live.com",
        age: "75",
        address: "Disputanta",
    },
    {
        givenName: "Charles",
        surName: "Kelly",
        email: "ckelly92@hotmail.com",
        age: "71",
        address: "Hastings",
    },
    {
        givenName: "David",
        surName: "Davis",
        email: "davidjoseph89@gmail.com",
        age: "36",
        address: "Sioux Falls",
    },
    {
        givenName: "Jeremy",
        surName: "Reed",
        email: "je@outlook.com",
        age: "73",
        address: "Chandler",
    },
    {
        givenName: "Aaron",
        surName: "Howard",
        email: "a_w_howard@outlook.com",
        age: "75",
        address: "Sylvan Grove",
    },
    {
        givenName: "Anna",
        surName: "Bennett",
        email: "a_m@rocketmail.com",
        age: "34",
        address: "Salisbury Mills",
    },
    {
        givenName: "Anna",
        surName: "Baker",
        email: "a.baker64@outlook.com",
        age: "28",
        address: "Aurora",
    },
    {
        givenName: "Layla",
        surName: "Reed",
        email: "ln@gmail.com",
        age: "52",
        address: "Flat",
    },
    {
        givenName: "Alyssa",
        surName: "Adams",
        email: "alyssa_adams@outlook.com",
        age: "65",
        address: "Fairmont",
    },
    {
        givenName: "Rachel",
        surName: "Thompson",
        email: "r.thompson@live.com",
        age: "71",
        address: "Wilmington",
    },
    {
        givenName: "Kaitlyn",
        surName: "Long",
        email: "kllong@live.com",
        age: "23",
        address: "Jennings",
    },
    {
        givenName: "Patrick",
        surName: "Henderson",
        email: "patrickroberthenderson@yahoo.com",
        age: "35",
        address: "Smithville",
    },
    {
        givenName: "Lillian",
        surName: "Peterson",
        email: "l_m4@hotmail.com",
        age: "45",
        address: "Billings",
    },
    {
        givenName: "Jack",
        surName: "Williams",
        email: "jack.allen@hotmail.com",
        age: "40",
        address: "Arlington",
    },
    {
        givenName: "Jose",
        surName: "Ramirez",
        email: "josescottramirez38@hotmail.com",
        age: "53",
        address: "Mobile",
    },
    {
        givenName: "Haley",
        surName: "Hughes",
        email: "haley_hughes@rocketmail.com",
        age: "57",
        address: "Maple Plain",
    },
    {
        givenName: "James",
        surName: "Lee",
        email: "james_lee@yahoo.com",
        age: "53",
        address: "Springfield",
    },
    {
        givenName: "Anna",
        surName: "Powell",
        email: "ampowell@gmail.com",
        age: "71",
        address: "Alpine",
    },
    {
        givenName: "Oliver",
        surName: "Perry",
        email: "oliver_j_perry17@aol.com",
        age: "71",
        address: "Hollywood",
    },
    {
        givenName: "Tyler",
        surName: "Price",
        email: "t.e.price@live.com",
        age: "53",
        address: "Bryant",
    },
    {
        givenName: "Timothy",
        surName: "King",
        email: "tking62@ymail.com",
        age: "21",
        address: "Los Fresnos",
    },
    {
        givenName: "Jeremy",
        surName: "Simmons",
        email: "j.r.simmons@hotmail.com",
        age: "74",
        address: "Mount Carbon",
    },
    {
        givenName: "Michael",
        surName: "Bennett",
        email: "m.bennett@ymail.com",
        age: "63",
        address: "Stuttgart",
    },
    {
        givenName: "Sean",
        surName: "Wilson",
        email: "sean.wilson@live.com",
        age: "74",
        address: "Axtell",
    },
    {
        givenName: "Kevin",
        surName: "Lee",
        email: "k_t_lee@gmail.com",
        age: "75",
        address: "El Macero",
    },
    {
        givenName: "William",
        surName: "Williams",
        email: "w.williams@live.com",
        age: "48",
        address: "Springfield",
    },
    {
        givenName: "Amber",
        surName: "Carter",
        email: "ambercarter@rocketmail.com",
        age: "52",
        address: "Johnson City",
    },
    {
        givenName: "Brianna",
        surName: "Brown",
        email: "brianna.r.brown@live.com",
        age: "28",
        address: "Reva",
    },
    {
        givenName: "Laura",
        surName: "Evans",
        email: "l.r.evans@outlook.com",
        age: "34",
        address: "Albertville",
    },
    {
        givenName: "Thomas",
        surName: "Robinson",
        email: "thomas_robinson@live.com",
        age: "77",
        address: "Fine",
    },
    {
        givenName: "Alyssa",
        surName: "Ross",
        email: "alyssa.ross@gmail.com",
        age: "23",
        address: "Jackson",
    },
    {
        givenName: "Sara",
        surName: "Wright",
        email: "sara_l_wright@hotmail.com",
        age: "43",
        address: "Asheboro",
    },
    {
        givenName: "Stephanie",
        surName: "Jackson",
        email: "stephanie_mary_jackson@aol.com",
        age: "39",
        address: "Nonantum",
    },
    {
        givenName: "Elizabeth",
        surName: "Anderson",
        email: "eianderson@live.com",
        age: "44",
        address: "Blue Mounds",
    },
    {
        givenName: "Anthony",
        surName: "Young",
        email: "amyoung@aol.com",
        age: "25",
        address: "Ellwood City",
    },
    {
        givenName: "Brandon",
        surName: "Thompson",
        email: "brandoneugene@rocketmail.com",
        age: "24",
        address: "Hatboro",
    },
    {
        givenName: "Jason",
        surName: "Parker",
        email: "jason.a.parker@gmail.com",
        age: "70",
        address: "Onamia",
    },
    {
        givenName: "Joshua",
        surName: "Reed",
        email: "jreed@ymail.com",
        age: "37",
        address: "Cherry Point",
    },
    {
        givenName: "Nicole",
        surName: "Campbell",
        email: "nicole.r.campbell30@gmail.com",
        age: "47",
        address: "McKeesport",
    },
    {
        givenName: "Samuel",
        surName: "Rogers",
        email: "s_j_rogers@hotmail.com",
        age: "24",
        address: "Marietta",
    },
    {
        givenName: "Mark",
        surName: "Torres",
        email: "m.j.torres@yahoo.com",
        age: "23",
        address: "Bon Aqua",
    },
    {
        givenName: "Joshua",
        surName: "Martinez",
        email: "joshua.charles.martinez@aol.com",
        age: "73",
        address: "Pine Top",
    },
    {
        givenName: "Jonathan",
        surName: "Hernandez",
        email: "jonathanjosephhernandez@ymail.com",
        age: "42",
        address: "Kincaid",
    },
    {
        givenName: "Oliver",
        surName: "Richardson",
        email: "orichardson@aol.com",
        age: "45",
        address: "Lindrith",
    },
    {
        givenName: "Jasmine",
        surName: "Hughes",
        email: "jasmine.hughes53@yahoo.com",
        age: "25",
        address: "New Blaine",
    },
    {
        givenName: "Kyle",
        surName: "Hill",
        email: "khill@live.com",
        age: "18",
        address: "Shelbyville",
    },
    {
        givenName: "Victoria",
        surName: "Perez",
        email: "victoria.lee.perez@gmail.com",
        age: "63",
        address: "Los Altos",
    },
    {
        givenName: "Alexis",
        surName: "Scott",
        email: "ascott@hotmail.com",
        age: "30",
        address: "Salt Lake City",
    },
    {
        givenName: "Kyle",
        surName: "Miller",
        email: "kyleemiller@gmail.com",
        age: "73",
        address: "El Paso",
    },
    {
        givenName: "Chelsea",
        surName: "Reed",
        email: "c.reed@gmail.com",
        age: "66",
        address: "Davis Junction",
    },
    {
        givenName: "Daniel",
        surName: "Cox",
        email: "d_g@hotmail.com",
        age: "59",
        address: "Waldo",
    },
    {
        givenName: "Kevin",
        surName: "Ross",
        email: "kevinross11@rocketmail.com",
        age: "19",
        address: "Rosenberg",
    },
    {
        givenName: "Evelyn",
        surName: "Foster",
        email: "evelyn.r.foster@aol.com",
        age: "48",
        address: "Pittsburgh",
    },
    {
        givenName: "Eric",
        surName: "Lee",
        email: "emlee@rocketmail.com",
        age: "69",
        address: "Houston",
    },
    {
        givenName: "Eleanor",
        surName: "Cox",
        email: "eleanor_marie_cox95@live.com",
        age: "62",
        address: "McCall",
    },
    {
        givenName: "Charlotte",
        surName: "Howard",
        email: "choward@ymail.com",
        age: "23",
        address: "Conshohocken",
    },
    {
        givenName: "Stephen",
        surName: "Richardson",
        email: "s.c@gmail.com",
        age: "39",
        address: "Butler",
    },
    {
        givenName: "Alexis",
        surName: "Wilson",
        email: "alexis_kay_wilson@hotmail.com",
        age: "23",
        address: "Garfield",
    },
    {
        givenName: "Aiden",
        surName: "Russell",
        email: "aiden.m.russell@yahoo.com",
        age: "67",
        address: "Black Diamond",
    },
    {
        givenName: "Nathan",
        surName: "Hayes",
        email: "n.hayes13@live.com",
        age: "34",
        address: "Locust Fork",
    },
    {
        givenName: "Kelsey",
        surName: "Young",
        email: "kjyoung@rocketmail.com",
        age: "35",
        address: "Hawaiian Ocean View",
    },
    {
        givenName: "Jonathan",
        surName: "Parker",
        email: "jonathanaparker@aol.com",
        age: "31",
        address: "Summit",
    },
    {
        givenName: "Brittany",
        surName: "Moore",
        email: "brittany_moore60@ymail.com",
        age: "55",
        address: "East Texas",
    },
    {
        givenName: "Timothy",
        surName: "Scott",
        email: "timothy_scott@outlook.com",
        age: "53",
        address: "Paris",
    },
    {
        givenName: "Anna",
        surName: "Hall",
        email: "ahall@aol.com",
        age: "19",
        address: "Taberg",
    },
    {
        givenName: "Adam",
        surName: "Price",
        email: "a.r.price@gmail.com",
        age: "46",
        address: "Hart",
    },
    {
        givenName: "Mark",
        surName: "Henderson",
        email: "mark.wayne.henderson81@rocketmail.com",
        age: "21",
        address: "Gilman",
    },
    {
        givenName: "James",
        surName: "Ramirez",
        email: "j_ramirez80@yahoo.com",
        age: "70",
        address: "Dement",
    },
    {
        givenName: "Emma",
        surName: "Hill",
        email: "e_hill@yahoo.com",
        age: "35",
        address: "Biggs",
    },
    {
        givenName: "Emma",
        surName: "King",
        email: "emma.g.king@rocketmail.com",
        age: "69",
        address: "West Union",
    },
    {
        givenName: "Claire",
        surName: "Harris",
        email: "c_harris45@yahoo.com",
        age: "69",
        address: "Shiro",
    },
    {
        givenName: "Sara",
        surName: "Brown",
        email: "sara_brown@aol.com",
        age: "52",
        address: "Santee",
    },
    {
        givenName: "Tiffany",
        surName: "Gray",
        email: "tiffany_f_gray@aol.com",
        age: "28",
        address: "Pittsburgh",
    },
    {
        givenName: "Joshua",
        surName: "Lewis",
        email: "joshua.lewis@live.com",
        age: "41",
        address: "Viola",
    },
    {
        givenName: "Evelyn",
        surName: "Cox",
        email: "evelyn_j_cox@ymail.com",
        age: "51",
        address: "Unadilla",
    },
    {
        givenName: "Rebecca",
        surName: "Rogers",
        email: "rebecca.rogers@yahoo.com",
        age: "24",
        address: "Hampton",
    },
    {
        givenName: "Kyle",
        surName: "Jones",
        email: "kyle@hotmail.com",
        age: "59",
        address: "Cabo Rojo",
    },
    {
        givenName: "Dylan",
        surName: "Collins",
        email: "dylan_collins@live.com",
        age: "61",
        address: "Fort Benton",
    },
    {
        givenName: "David",
        surName: "Ward",
        email: "d.d.ward@rocketmail.com",
        age: "50",
        address: "Greensboro",
    },
    {
        givenName: "Jason",
        surName: "Williams",
        email: "jasonjosephwilliams@yahoo.com",
        age: "31",
        address: "Georgetown",
    },
];
